version: "3"

services:

###### Nginx ############
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

###### PHP ############
  php:
    build: 
      context: ./php
      args:
        - TZ=${TIMEZONE}
    expose:
      - "9000"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

###### MYSQL ############
  mysql:
    build:
      context: ./mysql
      args:
        - TZ=${TIMEZONE}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
