version: "3"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
  php:
    build: 
      context: ./php
      args:
        - TZ=${TIMEZONE}
    expose:
      - "9000"
