version: "3"

services:

###### Nginx ############
  nginx:
    build:
      context: ./nginx
    ports:
      - "${HOST_HTTP_PORT}:80"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

###### PHP ############
  php:
    build: 
      context: ./php/${PHP_VERSION}
      args:
        - PHP_COMPOSER_URL=${PHP_COMPOSER_URL}
        - PHP_COMPOSER_REPO=${PHP_COMPOSER_REPO}
        - TZ=${TIMEZONE}
    expose:
      - "9000"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

###### MYSQL ############
  mysql:
    build:
      context: ./mysql
      args:
        - TZ=${TIMEZONE}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql

### Redis ################################################
  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ${DATA_PATH_HOST}/redis:/data

### MongoDB ##############################################
  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data
